mlflow:
  experiment: sbsbs
  run: test


sbs:
  grid:
    dz: 10um
    zmax: 1cm
    zmin: 0mm

  units:
    atomic mass number: 13.0
    laser_intensity: 8.0e+15W/cm^2
    laser_wavelength: 351nm
    reference temperature: 1000.0eV
    reference density: nc  # or it can be a float value
    logLambda: nrl

  profiles:
    n: 
      min: 0.001nc
      max: 0.025nc
    Te: 1.4keV
    Ti: 450eV
    flow: 0.0m/s
    Zeff: 5
    lambdabeat: 5.293519e-10m

  initial conditions:
    Ji: 1.0
    Jr: 0.1

cbet:
  profiles:
    sbs: 
      ne_over_nc: 0.05
      T_e: 0.5  # keV
      T_i: 0.165  # keV
      Z_eff: 4.0
      A_ion: 4.0
      flow_magnitude: 1e-4  # u/c
      flow_theta: 0.0
      flow_phi: 0.0
      L_p: 600.0  # 2*pi*plasma_length/lambda
    cbet:
      n_over_n0: 0.05  # normalized density profile
      T_e_over_T_i: 3.0  # electron temperature over ion temperature ratio
      Z_eff: 4.0  # effective charge
      A_ion: 4.0  # ion mass number
      flow_magnitude: 1e-4  # flow magnitude in units of u/c
      flow_theta: 0.0  # flow polar angle in degrees
      flow_phi: 0.0  # flow azimuthal angle in radians
      L_p: 600.0  # plasma length in units of lambda

  laser:
    wavelength: 3510  # Angstrom
    # beam_file: /path/to/beam_file.txt  # path to the beam file
    # a0_sq: 1e-6  # initial a_0^2, assuming all beams have same initial intensity
    num_beams: 4
    thetas: [23.5, 30, 44.5, 50] # polar angles in degrees
    phis: [0, 0, 0, 0]  # azimuthal angles in radians
    dls: [0, 0, 1.8, 1.8]  # dlambda/lambda

  grid:
    n_steps: 10000

