grid:
  dz: 10um
  zmax: 1cm
  zmin: 0mm


mlflow:
  experiment: sbsbs
  run: test

solver: sbsbs-1d

units:
  atomic mass number: 40
  laser_intensity: 2.0e+14W/cm^2
  laser_wavelength: 351nm
  reference temperature: 1000.0eV
  reference density: nc  # or it can be a float value

profiles:
  n: 
    min: 0.001
    max: 0.025
  Te: 1.4keV
  Ti: 450eV
  flow: 0.0
  Zeff: 5
  omega_beat: 0.1nm
  a0: 0.1


initial conditions:
  Ji: 1.0
  Jr: 0.1