version: 2

updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
    timezone: "Europe/London"
  open-pull-requests-limit: 10

  groups:
    actions:
      patterns:
      - "*"
