units:
  laser_wavelength: 351nm
  normalizing_temperature: 2000eV
  normalizing_density: 1.5e21/cc
  Z: 10
  Zp: 10


density:
  quasineutrality: true
  species-background:
    noise_seed: 420
    noise_type: gaussian
    noise_val: 0.0
    v0: 0.0
    T0: 1.0
    m: 2.0
    basis: uniform
    baseline: 1.0
    bump_or_trough: bump
    center: 0.0
    rise: 25.0
    bump_height: 0.0
    width: 100000.0

grid:
  dt: 0.5
  nv: 2048
  nx: 128
  tmin: 0.
  tmax: 8000.0
  vmax: 6.4
  xmax: 20.94
  xmin: 0.0

save:
  fields:
    t:
      tmin: 0.0
      tmax: 8000.0
      nt: 16001
  electron:
    t:
      tmin: 0.0
      tmax: 8000.0
      nt: 801
  diag-vlasov-dfdt:
    t:
      tmin: 0.0
      tmax: 8000.0
      nt: 801
  diag-fp-dfdt:
    t:
      tmin: 0.0
      tmax: 8000.0
      nt: 801

solver: vlasov-1d

mlflow:
  experiment: freqshift-nuswitch
  run: a0-01-long-nu-1e-5-const

drivers:
  ex:
    '0':
      a0: 1.e-2
      k0: 0.3
      t_center: 500.0
      t_rise: 20.0
      t_width: 100.0
      w0: 1.1598
      dw0: 0.
      x_center: 0.0
      x_rise: 10.0
      x_width: 4000000.0
  ey: {}

diagnostics:
  diag-vlasov-dfdt: True
  diag-fp-dfdt: True

terms:
  field: poisson
  edfdv: exponential
  time: sixth
  fokker_planck:
    is_on: True
    type: dougherty
    time:
      baseline: 1.0e-8
      bump_or_trough: bump
      center: 10000.0
      rise: 200.0
      slope: 0.0
      bump_height: 1.0e-5
      width: 120000.0
    space:
      baseline: 1.0
      bump_or_trough: bump
      center: 0.0
      rise: 25.0
      slope: 0.0
      bump_height: 0.0
      width: 100000.0
  krook:
    is_on: False
    time:
      baseline: 1.0
      bump_or_trough: bump
      center: 0.0
      rise: 25.0
      slope: 0.0
      bump_height: 0.0
      width: 100000.0
    space:
      baseline: 1.0
      bump_or_trough: bump
      center: 0.0
      rise: 25.0
      slope: 0.0
      bump_height: 0.0
      width: 100000.0