units:
  normalizing_temperature: 1000eV
  normalizing_density: 1.0e19/cc
density:
  quasineutrality: true
  species-ion-background:
    noise_seed: 416
    noise_type: gaussian
    noise_val: 1.0e-06
    v0: 0.0
    T0: 1.0
    m: 2.0
    basis: uniform
    baseline: 1.0
grid:
  dt: 0.25
  nx: 2048
  tmin: 0.0
  tmax: 7168.0
  xmax: 1024.0
  xmin: 0.0
save:
  fields:
    t:
      nt: 717
  ion:
    main:
      t:
        tmin: 0.0
        tmax: 7168.0
        nt: 57
solver: vlasov-1d
mlflow:
  experiment: iaw-turbulence
  run: vortex-test-te-ti-1-leapfrog
drivers:
  ex: {}
  ey: {}
  ex_stochastic:
    modes:
    - 1
    amplitude: 0.00097656
    tau: 1024.0
    seed: 29
diagnostics:
  diag-vlasov-dfdt: false
  diag-fp-dfdt: false
terms:
  field: poisson-boltzmann
  boltzmann_electrons:
    Te: 1.0
  edfdv: cubic-spline
  time: leapfrog
  species:
  - name: ion
    charge: 1.0
    mass: 1.0
    vmax: 6.4
    nv: 512
    density_components:
    - species-ion-background
  fokker_planck:
    is_on: false
    type: Dougherty
    time:
      baseline: 1.0
      bump_or_trough: bump
      center: 0.0
      rise: 25.0
      slope: 0.0
      bump_height: 0.0
      width: 100000.0
    space:
      baseline: 1.0
      bump_or_trough: bump
      center: 0.0
      rise: 25.0
      slope: 0.0
      bump_height: 0.0
      width: 100000.0
  krook:
    is_on: false
    time:
      baseline: 1.0
      bump_or_trough: bump
      center: 0.0
      rise: 25.0
      slope: 0.0
      bump_height: 0.0
      width: 100000.0
    space:
      baseline: 1.0
      bump_or_trough: bump
      center: 0.0
      rise: 25.0
      slope: 0.0
      bump_height: 0.0
      width: 100000.0
