units:
  laser wavelength: 351nm
  normalizing temperature: 2000eV
  normalizing density: 1.5e21/cc
  Z: 10
  Zp: 10


density:
  quasineutrality: true
  species-background:
    noise_seed: 420
    noise_type: gaussian
    noise_val: 0.0
    v0: 0.0
    T0: 1.0
    m: 2.0
    basis: uniform
    space-profile:
      baseline: 1.0
      bump_or_trough: bump
      center: 0.0
      rise: 25.0
      slope: 0.0
      wall_height: 0.0
      width: 100000.0
grid:
  c_light: 10
  dt: 0.5
  nv: 1024
  nx: 1024
  tmin: 0.
  tmax: 1000.0
  vmax: 6.4
  xmax: 4000.0
  xmin: 0.0

save:
  fields:
    t:
      tmin: 0.0
      tmax: 1000.0
      nt: 512
  electron:
    t:
      tmin: 0.0
      tmax: 1000.0
      nt: 9

mode: vlasov-1d

mlflow:
  experiment: epw-finite-length-compare
  run: vlasov

drivers:
  ex:
    '0':
      a0: 1.e-3
      k0: 0.3
      t_center: 70.0
      t_rise: 5.0
      t_width: 100.0
      w0: 1.13
      dw0: 0.
      x_center: 1400.0
      x_rise: 20.0
      x_width: 600.0
  ey: {}

nuee: 0.0