density:
  quasineutrality: true
  species-background:
    T0: 1.0
    basis: uniform
    m: 2.0
    noise_seed: 420
    noise_type: gaussian
    noise_val: 0.0
    space-profile:
      baseline: 1.0
      bump_or_trough: bump
      center: 0.0
      rise: 25.0
      slope: 0.0
      wall_height: 0.0
      width: 100000.0
    v0: 0.0
drivers:
  ex:
    '0':
      a0: 0.01
      dw0: 0.0
      k0: 0.28
      t_center: 60.0
      t_rise: 5.0
      t_width: 80.0
      w0: 1.1370461486881023
      x_center: 600.0
      x_rise: 20.0
      x_width: 900.0
  ey: {}
grid:
  c_light: 10
  dt: 0.1
  nv: 6144
  nx: 4096
  tmax: 1000.0
  tmin: 0.0
  vmax: 6.4
  xmax: 4000.0
  xmin: 0.0
mlflow:
  experiment: wavepacket-k-nu-a-vlasov-hr-sl
  run: vlasov-absorbing
solver: vlasov-1d
save:
  electron:
    t:
      nt: 51
      tmax: 1000.0
      tmin: 0.0
  fields:
    t:
      nt: 1001
      tmax: 1000.0
      tmin: 0.0

diagnostics:
  diag-vlasov-dfdt: False
  diag-fp-dfdt: False
  
terms:
  field: poisson
  edfdv: cubic-spline
  time: leapfrog
  fokker_planck:
    is_on: true
    space:
      baseline: 1.0
      bump_height: 0.0
      bump_or_trough: bump
      center: 0.0
      rise: 25.0
      slope: 0.0
      width: 100000.0
    time:
      baseline: 1.0e-05
      bump_height: 0.0
      bump_or_trough: bump
      center: 0.0
      rise: 25.0
      slope: 0.0
      width: 100000.0
    type: Dougherty
  krook:
    is_on: true
    space:
      baseline: 0.0001
      bump_height: 1.0
      bump_or_trough: trough
      center: 2000.0
      rise: 20.0
      slope: 0.0
      width: 3800.0
    time:
      baseline: 1.0
      bump_height: 0.0
      bump_or_trough: bump
      center: 0.0
      rise: 25.0
      slope: 0.0
      width: 100000.0
units:
  Z: 10
  Zp: 10
  laser_wavelength: 351nm
  normalizing_density: 1.5e21/cc
  normalizing_temperature: 2000eV