density:
  quasineutrality: true
  species-electron-background:
    T0: 1.0
    basis: uniform
    m: 2.0
    noise_seed: 420
    noise_type: gaussian
    noise_val: 0.0
    space-profile:
      baseline: 1.0
      bump_or_trough: bump
      center: 0.0
      rise: 25.0
      slope: 0.0
      wall_height: 0.0
      width: 100000.0
    v0: 0.0
  species-ion-background:
    noise_seed: 421
    noise_type: gaussian
    noise_val: 0.0
    v0: 0.0
    T0: 0.01
    m: 2.0
    basis: sine
    baseline: 1.0
    amplitude: 0.0e-3
    wavenumber: 0.1
drivers:
  ex:
    '0':
      a0: 0.01
      dw0: 0.0
      k0: 0.28
      t_center: 60.0
      t_rise: 5.0
      t_width: 80.0
      w0: 1.1370461486881023
      x_center: 600.0
      x_rise: 20.0
      x_width: 900.0
  ey: {}
grid:
  c_light: 10
  dt: 0.1
  nx: 4096
  tmax: 1000.0
  tmin: 0.0
  xmax: 4000.0
  xmin: 0.0
  nv: 2048
  vmax: 6.4
mlflow:
  experiment: wavepacket-parallel
  run: test
solver: vlasov-1d
save:
  electron:
    t:
      nt: 51
      tmax: 1000.0
      tmin: 0.0
    x:
      nx: 256
      xmax: 4000.0
      xmin: 0.0
    v:
      nv: 256
      vmax: 6.4
      vmin: -6.4

  fields:
    t:
      nt: 1001
      tmax: 1000.0
      tmin: 0.0

diagnostics:
  diag-vlasov-dfdt: False
  diag-fp-dfdt: False

terms:
  field: poisson
  edfdv: cubic-spline
  time: leapfrog
  x_parallel: true
  # species:
  #   - name: electron
  #     charge: -1.0
  #     mass: 1.0
  #     vmax: 6.4
  #     nv: 2048
  #     density_components:
  #       - species-electron-background
  #   - name: ion
  #     charge: 1.0
  #     mass: 183600.0
  #     vmax: 0.15
  #     nv: 256
  #     density_components:
  #       - species-ion-background
  fokker_planck:
    is_on: true
    space:
      baseline: 1.0
      bump_height: 0.0
      bump_or_trough: bump
      center: 0.0
      rise: 25.0
      slope: 0.0
      width: 100000.0
    time:
      baseline: 1.0e-05
      bump_height: 0.0
      bump_or_trough: bump
      center: 0.0
      rise: 25.0
      slope: 0.0
      width: 100000.0
    type: Dougherty
  krook:
    is_on: False
    space:
      baseline: 0.0001
      bump_height: 1.0
      bump_or_trough: trough
      center: 2000.0
      rise: 20.0
      slope: 0.0
      width: 3800.0
    time:
      baseline: 1.0
      bump_height: 0.0
      bump_or_trough: bump
      center: 0.0
      rise: 25.0
      slope: 0.0
      width: 100000.0
units:
  Z: 10
  Zp: 10
  laser_wavelength: 351nm
  normalizing_density: 1.5e21/cc
  normalizing_temperature: 2000eV
