units:
  laser_wavelength: 351nm
  normalizing_temperature: 2000eV
  normalizing_density: 1.5e21/cc
  Z: 10
  Zp: 10
  A: 1.0  # Ion mass number (protons)

density:
  quasineutrality: true
  species-background:
    noise_seed: 420
    noise_type: gaussian
    noise_val: 0.0
    v0: 0.0
    T0: 1.0
    m: 2.0
    basis: uniform
    baseline: 1.0
    bump_or_trough: bump
    center: 0.0
    rise: 25.0
    bump_height: 0.0
    width: 100000.0
  species-ion:
    noise_seed: 421
    noise_type: gaussian
    noise_val: 0.0
    v0: 0.0  # Ion drift velocity
    T0: 0.5  # Ion temperature directly (0.1 = Ti/Te = 0.1)
    m: 2.0   # Maxwellian (m=2)
    basis: uniform
    baseline: 1.0
    bump_or_trough: bump
    center: 0.0
    rise: 25.0
    bump_height: 0.0
    width: 100000.0

grid:
  dt: 0.1
  nv: 512
  nv_i: 128
  nx: 10240
  tmin: 0.
  tmax: 50000.0
  vmax: 6.4
  xmax: 10000.0
  xmin: 0.0

save:
  fields:
    t:
      tmin: 0.0
      tmax: 50000.0
      nt: 5001
  electron:
    t:
      tmin: 0.0
      tmax: 50000.0
      nt: 101
  ion:
    t:
      tmin: 0.0
      tmax: 50000.0
      nt: 101

solver: vlasov-2s1d

mlflow:
  experiment: 2species-epw
  run: basic-test

drivers:
  ex:
    '0':
      a0: 5.e-2
      k0: 0.06
      t_center: 100.0
      t_rise: 5.0
      t_width: 100.0
      w0: 1.005
      dw0: 0.
      x_center: 2000.0
      x_rise: 100.0
      x_width: 2000.0
  ey: {}

diagnostics:
  diag-vlasov-dfdt: False
  diag-fp-dfdt: False 

terms:
  field: poisson
  edfdv: exponential  # Using exponential for stability with 2-species
  time: leapfrog  # Only leapfrog implemented for 2-species
  fokker_planck:
    is_on: False
    type: lenard_bernstein  # Can be lenard_bernstein or dougherty
    time:
      baseline: 1.0e-5
      bump_or_trough: bump
      center: 0.0
      rise: 25.0
      slope: 0.0
      bump_height: 0.0
      width: 100000.0
    space:
      baseline: 1.0
      bump_or_trough: bump
      center: 0.0
      rise: 25.0
      slope: 0.0
      bump_height: 0.0
      width: 100000.0
  krook:
    is_on: False
    time:
      baseline: 1.0
      bump_or_trough: bump
      center: 0.0
      rise: 25.0
      slope: 0.0
      bump_height: 0.0
      width: 100000.0
    space:
      baseline: 1.0
      bump_or_trough: bump
      center: 0.0
      rise: 25.0
      slope: 0.0
      bump_height: 0.0
      width: 100000.0
