units:
  laser_wavelength: 351nm
  normalizing_temperature: 1000eV
  normalizing_density: 1e21/cc
  Z: 1
  Zp: 1
  A: 1.0  # Hydrogen ions

density:
  quasineutrality: true
  species-background:
    noise_seed: 789
    noise_type: gaussian
    noise_val: 1.e-6
    v0: 0.0
    T0: 1.0
    m: 1.0
    basis: cosine
    mode: 1
    baseline: 1.0
    bump_or_trough: bump
    center: 0.0
    rise: 25.0
    bump_height: 0.05  # Small perturbation for linear regime
    width: 100000.0
  species-ion:
    noise_seed: 790
    noise_type: gaussian
    noise_val: 0.0
    v0: 0.0
    T0: 0.5  # Moderate ion temperature for ion acoustic waves
    m: 2.0
    basis: uniform
    baseline: 1.0
    bump_or_trough: bump
    center: 0.0
    rise: 25.0
    bump_height: 0.0
    width: 100000.0

grid:
  dt: 0.01  # Small timestep for ion dynamics
  nv: 192
  nx: 128
  tmin: 0.
  tmax: 100.0  # Long time for ion acoustic oscillations
  vmax: 6.0
  xmax: 31.416  # 5*pi for long wavelength
  xmin: 0.0

save:
  fields:
    t:
      tmin: 0.0
      tmax: 100.0
      nt: 1001
  electron:
    t:
      tmin: 0.0
      tmax: 100.0
      nt: 101
  ion:
    t:
      tmin: 0.0
      tmax: 100.0
      nt: 101
  # Save ion moments for acoustic wave analysis
  diag:
    t:
      tmin: 0.0
      tmax: 100.0
      nt: 1001

solver: vlasov-2s1d

mlflow:
  experiment: 2species-waves
  run: ion-acoustic-test

drivers:
  ex: {}
  ey: {}

diagnostics:
  diag-vlasov-dfdt: False
  diag-fp-dfdt: False

terms:
  field: poisson
  edfdv: exponential
  time: leapfrog
  fokker_planck:
    is_on: True  # Light collisions to show effect on damping
    type: lenard_bernstein
    time:
      baseline: 0.01  # Weak collisions
      bump_or_trough: bump
      center: 0.0
      rise: 25.0
      slope: 0.0
      bump_height: 0.0
      width: 100000.0
    space:
      baseline: 1.0
      bump_or_trough: bump
      center: 0.0
      rise: 25.0
      slope: 0.0
      bump_height: 0.0
      width: 100000.0
  krook:
    is_on: False
    time:
      baseline: 0.0
      bump_or_trough: bump
      center: 0.0
      rise: 25.0
      slope: 0.0
      bump_height: 0.0
      width: 100000.0
    space:
      baseline: 1.0
      bump_or_trough: bump
      center: 0.0
      rise: 25.0
      slope: 0.0
      bump_height: 0.0
      width: 100000.0
