units:
  laser_wavelength: 351nm
  reference electron temperature: 500eV
  reference ion temperature: 500eV
  reference electron density: 1.5e21/cm^3
  Z: 30
  Ion: Au+
  logLambda: nrl


density:
  quasineutrality: true
  species-background:
    noise_seed: 420
    noise_type: gaussian
    noise_val: 0.0
    v0: 0.0
    T0: 1.0
    m: 2.0
    n: 
      basis: uniform
      baseline: 1.0
      bump_or_trough: bump
      center: 0.0um
      rise: 25.0um
      bump_height: 0.0
      width: 100000.0m
    T:
      basis: tanh
      baseline: 1.0
      bump_or_trough: bump
      center: 50um
      rise: 5um
      bump_height: 0.1
      width: 20um

grid:
  dt: 2.5fs
  nv: 512
  nx: 512
  tmin: 0.
  tmax: 1ps
  vmax: 8.0
  xmax: 100um
  xmin: 0.0um
  nl: 1

save:
  fields:
    t:
      tmin: 0.0ps
      tmax: 1ps
      nt: 11
  electron:
    t:
      tmin: 0.0ps
      tmax: 1ps
      nt: 6

solver: vfp-1d

mlflow:
  experiment: vfp2d
  run: hotspot

drivers:
  ex: {}
  ey: {}

terms:
  fokker_planck:
    flm:
      ee: True
    f00:
      type: Dougherty
  e_solver: oshun
    