units:
  laser_wavelength: 351nm
  normalizing_temperature: 2000eV
  normalizing_density: 1.5e21/cc
  Z: 10
  Zp: 10


density:
  quasineutrality: true
  species-background:
    noise_seed: 420
    noise_type: gaussian
    noise_val: 0.0
    v0: 0.0
    T0: 1.0
    m: 2.0
    basis: uniform
    baseline: 1.0
    bump_or_trough: bump
    center: 0.0
    rise: 25.0
    bump_height: 0.0
    width: 100000.0

grid:
  dt: 0.1
  nv: 1024
  nx: 32
  tmin: 0.
  tmax: 1000.0
  vmax: 8.0
  xmax: 20.94
  xmin: 0.0

save:
  fields:
    t:
      tmin: 0.0
      tmax: 1000.0
      nt: 1001
  electron-fx-vx:
    t:
      tmin: 0.0
      tmax: 1000.0
      nt: 101
    x: {}
    vx:
      vxmin: 0.0
      vxmax: 8.0
      nvx: 512
  electron-full:
    t:
      tmin: 0.0
      tmax: 1000.0
      nt: 6

solver: vlasov-1d2v

mlflow:
  experiment: 1d2v-epw
  run: a1em2-both-exact

drivers:
  ex:
    '0':
      a0: 1.e-2
      k0: 0.3
      t_center: 40.0
      t_rise: 5.0
      t_width: 30.0
      w0: 1.1598
      dw0: 0.
      x_center: 0.0
      x_rise: 10.0
      x_width: 4000000.0
  ey: {}

terms:
  field: poisson
  edfdv: exponential
  time: sixth
  fokker_planck:
    nu_ee: 
      is_on: true
      time:
        baseline: 1.0e-4
        bump_or_trough: bump
        center: 0.0
        rise: 25.0
        slope: 0.0
        bump_height: 0.0
        width: 100000.0
      space:
        baseline: 1.0
        bump_or_trough: bump
        center: 0.0
        rise: 25.0
        slope: 0.0
        bump_height: 0.0
        width: 100000.0
    nu_ei: 
      nr: 384
      nth: 2048
      solver: exact-fft
      is_on: true
      time:
        baseline: 1.0e-4
        bump_or_trough: bump
        center: 0.0
        rise: 25.0
        slope: 0.0
        bump_height: 0.0
        width: 100000.0
      space:
        baseline: 1.0
        bump_or_trough: bump
        center: 0.0
        rise: 25.0
        slope: 0.0
        bump_height: 0.0
        width: 100000.0
    