density:
  basis: uniform
  noise:
    max: 1.0e-09
    min: 1.0e-10
    type: uniform
drivers:
  E2: 
    envelope:
      tw: 200fs
      tr: 25fs
      tc: 150fs
      xw: 500um
      xc: 10um
      xr: 0.2um
      yr: 0.2um
      yc: 0um
      yw: 50um
    a0: 1000
    k0: -10.0
    w0: 20.0  # 1.5 k^2 vth^2 / wp0

grid:
  boundary_abs_coeff: 1.0e4
  boundary_width: 8um
  low_pass_filter: 0.7
  dt: 0.002ps
  dx: 20nm
  xmax: 6.28um
  tmax: 4.0ps
  tmin: 0.0ns
  ymax: 1um
  ymin: -1um

mlflow:
  experiment: test-lpse
  run: epw-test
save:
  fields:
    t:
      dt: 100fs
      tmax: 4ps
      tmin: 0ps
    x:
      dx: 22nm
    y:
      dy: 22nm
solver: envelope-2d
terms:
  epw:
    boundary:
      x: periodic
      y: periodic
    damping:
      collisions: false
      landau: false
    density_gradient: false
    linear: True
    source:
      noise: false
      tpd: false
  zero_mask: false
units:
  atomic number: 40
  envelope density: 0.25
  ionization state: 6
  laser intensity: 3.5e+14W/cm^2
  laser_wavelength: 351nm
  reference electron temperature: 2000.0eV
  reference ion temperature: 1000eV

