density:
  basis: linear
  gradient scale length: 200.0um
  max: 0.3
  min: 0.2
  noise:
    max: 1.0e-09
    min: 1.0e-10
    type: uniform
drivers:
  E0:
    amplitude_shape: uniform
    # file: s3://public-ergodic-continuum/87254/0bb528f5a431439e9f9f295bdcd6d9e7/artifacts/used_driver.pkl
    delta_omega_max: 0.015
    num_colors: 1

  E2: 
    tw: 200fs
    tr: 25fs
    tc: 150fs
    xw: 2um
    xc: 50um
    xr: 0.2um
    a0: 0.1
    k0: 140.0
    w0: 2683.0  # 1.5 k^2 vth^2 / wp0

grid:
  boundary_abs_coeff: 1.0e4
  boundary_width: 8um
  low_pass_filter: 0.7
  dt: 0.002ps
  dx: 20nm
  tmax: 2.0ps
  tmin: 0.0ns
  ymax: 4um
  ymin: -4um
machine:
  calculator: gpu
mlflow:
  experiment: test-lpse
  run: epw-test
save:
  t:
    dt: 100fs
    tmax: 2ps
    tmin: 0ps
  x:
    dx: 48nm
  y:
    dy: 160nm
solver: envelope-2d
terms:
  epw:
    boundary:
      x: periodic
      y: periodic
    damping:
      collisions: false
      landau: true
    density_gradient: false
    linear: true
    source:
      noise: false
      tpd: false
  zero_mask: true
units:
  atomic number: 40
  envelope density: 0.25
  ionization state: 6
  laser intensity: 3.5e+14W/cm^2
  laser wavelength: 351nm
  reference electron temperature: 2000.0eV
  reference ion temperature: 1000eV

