density:
  basis: linear
  gradient scale length: 366um
  max: 0.32
  min: 0.23
  noise:
    max: 1.0e-09
    min: 1.0e-10
    type: uniform
drivers:
  E0:
    delta_omega_max: 0.015
    envelope:
      tc: 200.25ps
      tr: 0.1ps
      tw: 400ps
      xc: 50um
      xr: 0.2um
      xw: 1000um
      yc: 50um
      yr: 0.2um
      yw: 1000um
    num_colors: 64
    shape: generative
    output: 
      amp: log       # or linear
      phase: random  # or learned

    params:
      decoder_depth: 3
      decoder_width: 128
      input_width: 8
      key: 906
      activation: relu

grid:
  boundary_abs_coeff: 1.0e4
  boundary_width: 3um
  dt: 2fs
  dx: 30nm
  low_pass_filter: 0.6
  tmax: 10.0ps
  tmin: 0.0ns
  ymax: 8um
  ymin: -8um
machine:
  calculator: gpu
mlflow:
  experiment: new-lpse-modules
  run: gen-test
save:
  fields:
    t:
      dt: 1ps
      tmax: 10ps
      tmin: 0ps
    x:
      dx: 80nm
    y:
      dy: 128nm
solver: envelope-2d
terms:
  epw:
    boundary:
      x: absorbing
      y: periodic
    damping:
      collisions: false
      landau: true
    density_gradient: true
    linear: true
    source:
      noise: true
      tpd: true
  zero_mask: true
units:
  atomic number: 40
  envelope density: 0.25
  ionization state: 6
  laser intensity: 7.53e14 W/cm^2
  laser wavelength: 351nm
  reference electron temperature: 3.92keV
  reference ion temperature: 1000eV
opt:
  learning_rate: 0.001
  batch_size: 4
  decay_steps: 60