models:
  bandwidth:
    file: None
    hyperparams:
      input_width: 8
      key: 42
      decoder_width: 16
      decoder_depth: 3
      output_width: 8
    type: GEN
opt:
  learning_rate: 0.003
  optimizer: adam
density:
  basis: linear
  gradient scale length: 200.0um
  max: 0.35
  min: 0.18
  noise:
    max: 1.0e-09
    min: 1.0e-10
    type: uniform
drivers:
  E0:
    amplitude_shape: uniform
    delta_omega_max: 0.015
    num_colors: 8
grid:
  boundary_abs_coeff: 1.0e4
  boundary_width: 8um
  low_pass_filter: 0.7
  dt: 0.002ps
  dx: 20nm
  tmax: 5.0ps
  tmin: 0.0ns
  ymax: 5um
  ymin: -5um

mlflow:
  experiment: tpd-gen-nc-8-nonu
  run: kfilt
save:
  t:
    dt: 100fs
    tmax: 5ps
    tmin: 0ps
  x:
    dx: 48nm
  y:
    dy: 160nm
solver: envelope-2d
terms:
  epw:
    boundary:
      x: absorbing
      y: periodic
    damping:
      collisions: false
      landau: true
    density_gradient: true
    linear: true
    source:
      noise: true
      tpd: true
  zero_mask: true
units:
  atomic number: 40
  envelope density: 0.25
  ionization state: 6
  laser intensity: 2.0e+15W/cm^2
  laser_wavelength: 351nm
  reference electron temperature: 2000.0eV
  reference ion temperature: 1000eV