density:
  basis: linear
  gradient scale length: 400.0um
  noise:
    max: 1.0e-09
    min: 1.0e-10
    type: uniform
  max: 0.35
  min: 0.15
drivers:
  E0:
    amplitude_shape: opt
    delta_omega_max: 0.015
    num_colors: 64
grid:
  dx: 20nm
  dt: 0.002ps
  tmax: 5.0ps
  tmin: 0.0ns
  xmax: 61um
  xmin: 0.0um
  ymax: 5um
  ymin: -5um
  boundary_abs_coeff: 100
machine:
  calculator: gpu
mlflow:
  experiment: tpd-gen-2e15-4000-400
  run: uniform
solver: envelope-2d

models:
  bandwidth:
    file: None
    hyperparams:
      input_width: 8
      key: 248
      decoder_width: 16
      decoder_depth: 3
      output_width: 64
    type: GEN
opt:
  learning_rate: 0.003
  optimizer: adam
save:
  t:
    dt: 100fs
    tmax: 5ps
    tmin: 0ps
  x:
    dx: 128nm

  y:
    dy: 128nm

terms:
  epw:
    boundary:
      x: absorbing
      y: periodic
    density_gradient: true
    kinetic real part: false
    linear: true
    source:
      noise: true
      tpd: true
    trapping:
      active: false
      kld: 0.28
      nuee: 1.0e-07
units:
  atomic number: 40
  envelope density: 0.25
  ionization state: 6
  laser intensity: 2.0e+15W/cm^2
  laser wavelength: 351nm
  reference electron temperature: 4000eV
  reference ion temperature: 1000eV