density:
  basis: linear
  gradient scale length: 200.0um
  max: 0.35
  min: 0.15
  noise:
    max: 1.0e-09
    min: 1.0e-10
    type: uniform
drivers:
  E0:
    amplitude_shape: uniform
    # file: s3://public-ergodic-continuum/83190/cc1e022b6c9c4bc7abc38bda90299b96/artifacts/used_driver.pkl
    delta_omega_max: 0.015
    num_colors: 1
grid:
  dt: 0.002ps
  dx: 20nm
  tmax: 2.0ps
  tmin: 0.0ns
  ymax: 5um
  ymin: -5um
  boundary_abs_coeff: 100000
machine:
  calculator: gpu
mlflow:
  experiment: tpd-two-lines
  run: mono-4e14
save:
  t:
    dt: 50fs
    tmax: 2ps
    tmin: 0ps
  x:
    dx: 128nm
  y:
    dy: 128nm
solver: envelope-2d
terms:
  epw:
    boundary:
      x: absorbing
      y: periodic
    density_gradient: true
    kinetic real part: false
    linear: true
    source:
      noise: true
      tpd: true
    trapping:
      active: false
      kld: 0.28
      nuee: 1.0e-07
units:
  atomic number: 40
  envelope density: 0.25
  ionization state: 6
  laser intensity: 4.0e+14W/cm^2
  laser wavelength: 351nm
  reference electron temperature: 2500eV
  reference ion temperature: 1000eV