density:
  noise:
    max: 1.0e-06
    min: 1.0e-05
    type: uniform
  gradient scale length: 162.5um
  val at center: 0.95
  center: 2500.0
drivers:
  E0:
    a0: doesnt_matter
    intensity: 1.0e5 W/cm^2
    k0: 1.0
    t_c: 500.0
    t_r: 20.0
    t_w: 600.0
    w0: 2.0
    x_c: 500.0
    x_r: 20.0
    x_w: 600.0
    y_c: 500.0
    y_r: 20.0
    y_w: 60000000.0
grid:
  dt: 2.0
  nx: 4096
  ny: 512
  tmax: 20000.0
  tmin: 0.0
  xmax: 5000.0
  xmin: 0.0
  ymax: 1000.0
  ymin: -1000.0
mlflow:
  experiment: lpse2d-tpd
  run: tpd-test-no-pump-evolution
mode: envelope-2d
plasma:
  Z: 2
  density: 2.3e27
  nb: 1.0
  nu_ei: 0.0
  temperature: 2.0
  wp0: 1.0
save:
  t:
    nt: 32
    tmax: 20000.0
    tmin: 0.0
terms:
  epw:
    boundary:
      x: absorbing
      y: periodic
    density_gradient: true
    kinetic real part: false
    linear: true
    source:
      tpd: true
    trapping:
      active: false
      kld: 0.28
      nuee: 1.0e-07
units:
  Z: 10
  Zp: 10
  electron temperature: 2000eV
  gas fill: N
  ionization state: 6
  laser wavelength: 351nm
  normalizing density: 1.5e21/cc
  normalizing temperature: 2000eV