density:
  basis: linear
  noise:
    max: 1.0e-09
    min: 1.0e-10
    type: uniform
  gradient scale length: 180um
  val at center: 0.2
drivers:
  E0:
    k0: 1.0
    t_c: 500.0
    t_r: 20.0
    t_w: 600.0
    w0: 2.0
    x_c: 500.0
    x_r: 20.0
    x_w: 600.0
    y_c: 500.0
    y_r: 20.0
    y_w: 60000000.0
grid:
  dx: 16nm
  tmax: 5.0ps
  tmin: 0.0ns
  xmax: 32um
  xmin: 0.0um
  ymax: 8um
  ymin: -8um
mlflow:
  experiment: lpse2d-tpd
  run: tpd-test-no-pump-evolution
mode: envelope-2d

save:
  t:
    dt: 100fs
    tmax: 5ps
    tmin: 0ps
terms:
  epw:
    boundary:
      x: absorbing
      y: periodic
    density_gradient: false
    kinetic real part: false
    linear: true
    source:
      tpd: true
    trapping:
      active: false
      kld: 0.28
      nuee: 1.0e-07
units:
  reference electron temperature: 2000eV
  reference ion temperature: 100eV
  ionization state: 6
  atomic number: 40
  laser wavelength: 351nm
  laser intensity: 1e14W/cm^2
  envelope density: 0.25