density:
  basis: linear
  noise:
    max: 1.0e-09
    min: 1.0e-10
    type: uniform
  gradient scale length: 200um
  val at center: 0.25

drivers:
  E0:
    num_colors: 64
    delta_omega_max: 0.03
    amplitude_shape: lorentzian

grid:
  dx: 24nm
  tmax: 8.0ps
  tmin: 0.0ns
  xmax: 61um
  xmin: 0.0um
  ymax: 5um
  ymin: -5um
mlflow:
  experiment: lpse2d-tpd-learn
  run: baseline-lorentzian
mode: envelope-2d

save:
  t:
    dt: 100fs
    tmax: 8ps
    tmin: 0ps
terms:
  epw:
    boundary:
      x: absorbing
      y: periodic
    density_gradient: true
    kinetic real part: false
    linear: true
    source:
      tpd: true
      noise: true
    trapping:
      active: false
      kld: 0.28
      nuee: 1.0e-07
units:
  reference electron temperature: 2000eV
  reference ion temperature: 1000eV
  ionization state: 6
  atomic number: 40
  laser wavelength: 351nm
  laser intensity: 3e15W/cm^2
  envelope density: 0.25

machine:
  calculator: gpu