density:
  basis: linear
  gradient scale length: 200.0um
  max: 0.28
  min: 0.22
  noise:
    max: 1.0e-09
    min: 1.0e-10
    type: uniform
drivers:
  E0:
    amplitude_shape: uniform
    # file: s3://public-ergodic-continuum/83190/cc1e022b6c9c4bc7abc38bda90299b96/artifacts/used_driver.pkl
    delta_omega_max: 0.01
    num_colors: 2
grid:
  dt: 0.002ps
  dx: 20nm
  tmax: 10.0ps
  tmin: 0.0ns
  ymax: 5um
  ymin: -5um
  boundary_abs_coeff: 10000
  boundary_width: 8um
machine:
  calculator: gpu
mlflow:
  experiment: k0
  run: noise-dn
save:
  t:
    dt: 50fs
    tmax: 5ps
    tmin: 0ps
  x:
    dx: 100nm
  y:
    dy: 100nm
solver: envelope-2d
terms:
  epw:
    boundary:
      x: absorbing
      y: periodic
    density_gradient: true
    linear: true
    source:
      noise: true
      tpd: false
units:
  atomic number: 40
  envelope density: 0.25
  ionization state: 6
  laser intensity: 0.0e+14W/cm^2
  laser wavelength: 351nm
  reference electron temperature: 2500eV
  reference ion temperature: 1000eV