mode: envelope-2d

drivers:
  E0:
    w0: 2.0
    t_c: 500.
    t_w: 600.
    t_r: 20.
    x_c: 500.
    x_w: 600.
    x_r: 20.
    y_c: 500.
    y_w: 60000000.
    y_r: 20.
    k0: 1.0
    a0: 0.0
    intensity: 4.0e14
  E2:
    w0: 0.135
    t_c: 400.
    t_w: 760.
    t_r: 5.
    x_c: 1000.
    x_w: 800.
    x_r: 20.
    y_c: 0.
    y_w: 2000000.
    y_r: 5.
    k0: 0.2
    a0: 0.001
    intensity: 4.0e14

save:
  t:
    tmin: 10.0
    tmax: 3950.0
    nt: 400

plasma:
  wp0: 1.0
  nu_ei: 0.0
  Z: 2
  nb: 1.0
  temperature: 2.0 #keV
  density: 2.3e27  #m^3

grid:
  xmin: 000.0
  xmax: 4000.0
  nx: 2048
  ymin: -4.0
  ymax: 4.0
  ny: 8
  tmin: 0.
  tmax: 4000.0
  dt: 0.5

mlflow:
  experiment: lpse
  run: wavepacket

terms:
  epw:
    linear: True
    density_gradient: False
  tpd:
    source: False