density:
  basis: linear
  gradient scale length: 300.0um
  noise:
    max: 1.0e-09
    min: 1.0e-10
    type: uniform
  val at center: 0.25
drivers:
  E0:
    amplitude_shape: uniform
    delta_omega_max: 0.03
    num_colors: 64
grid:
  dx: 24nm
  tmax: 5.0ps
  tmin: 0.0ns
  xmax: 61um
  xmin: 0.0um
  ymax: 5um
  ymin: -5um
machine:
  calculator: gpu
mlflow:
  experiment: lpse2d-tpd-baselines
  run: baseline-uniform
mode: envelope-2d
model:
  hyperparams:
    decoder_depth: 2
    decoder_width: 4
    encoder_depth: 2
    encoder_width: 4
    input_width: 3
    key: 42
    latent_width: 4
    output_width: 64
  type: MLP
opt:
  learning_rate: 0.002
  optimizer: adam
save:
  t:
    dt: 40fs
    tmax: 5ps
    tmin: 0ps
terms:
  epw:
    boundary:
      x: absorbing
      y: periodic
    density_gradient: true
    kinetic real part: false
    linear: true
    source:
      noise: true
      tpd: true
    trapping:
      active: false
      kld: 0.28
      nuee: 1.0e-07
units:
  atomic number: 40
  envelope density: 0.25
  ionization state: 6
  laser intensity: 1.24e+15W/cm^2
  laser wavelength: 351nm
  reference electron temperature: 2666.6666666666665eV
  reference ion temperature: 1000eV