density:
  basis: linear
  noise:
    max: 1.0e-09
    min: 1.0e-10
    type: uniform
  gradient scale length: 120um
  val at center: 0.24
drivers:
  E0:
    k0: 1.0
    t_c: 500.0
    t_r: 20.0
    t_w: 600.0
    w0: 2.0
    x_c: 500.0
    x_r: 20.0
    x_w: 600.0
    y_c: 500.0
    y_r: 20.0
    y_w: 60000000.0
grid:
  dx: 16nm
  tmax: 4.0ps
  tmin: 0.0ns
  xmax: 50um
  xmin: 0.0um
  ymax: 10um
  ymin: -10um
mlflow:
  experiment: lpse2d-tpd
  run: tpd-test-no-pump-evolution
mode: envelope-2d

save:
  t:
    dt: 100fs
    tmax: 4ps
    tmin: 0ps
terms:
  epw:
    boundary:
      x: absorbing
      y: periodic
    density_gradient: true
    kinetic real part: false
    linear: true
    source:
      tpd: true
      noise: true
    trapping:
      active: false
      kld: 0.28
      nuee: 1.0e-07
units:
  reference electron temperature: 2000eV
  reference ion temperature: 1000eV
  ionization state: 6
  atomic number: 40
  laser wavelength: 351nm
  laser intensity: 1e15W/cm^2
  envelope density: 0.25