density:
  basis: linear
  gradient scale length: 300.0um
  max: 0.35
  min: 0.15
  noise:
    max: 1.0e-09
    min: 1.0e-10
    type: uniform
drivers:
  E0:
    amplitude_shape: file
    file: s3://public-ergodic-continuum/74766/b0bb9e4bc45944eeab6c9906fb0ca586/artifacts/used_driver.pkl
    delta_omega_max: 0.03
    num_colors: 64
grid:
  dt: 0.002ps
  dx: 16nm
  tmax: 20.0ps
  tmin: 0.0ns
  xmax: 61um
  xmin: 0.0um
  ymax: 5um
  ymin: -5um
machine:
  calculator: gpu
mlflow:
  experiment: tpd-gen-th-i45e13
  run: ml-long
save:
  t:
    dt: 100fs
    tmax: 20ps
    tmin: 0ps
  x:
    dx: 128nm
  y:
    dy: 128nm
solver: envelope-2d
terms:
  epw:
    boundary:
      x: absorbing
      y: periodic
    density_gradient: true
    kinetic real part: false
    linear: true
    source:
      noise: true
      tpd: true
    trapping:
      active: false
      kld: 0.28
      nuee: 1.0e-07
units:
  atomic number: 40
  envelope density: 0.25
  ionization state: 6
  laser intensity: 4.5e+14W/cm^2
  laser wavelength: 351nm
  reference electron temperature: 2000eV
  reference ion temperature: 1000eV