density:
  basis: linear
  gradient scale length: 200.0um
  noise:
    max: 1.0e-09
    min: 1.0e-10
    type: uniform
  max: 0.35
  min: 0.15
drivers:
  E0:
    amplitude_shape: opt
    delta_omega_max: 0.03
    num_colors: 64
grid:
  dx: 24nm
  tmax: 3.0ps
  tmin: 0.0ns
  xmax: 61um
  xmin: 0.0um
  ymax: 5um
  ymin: -5um
machine:
  calculator: gpu
mlflow:
  experiment: tpd-opt
  run: mono-newL
solver: envelope-2d

models:
  bandwidth:
    file: None
#     hyperparams:
#       decoder_depth: 2
#       decoder_width: 4
#       encoder_depth: 2
#       encoder_width: 4
#       input_width: 3
#       key: 42
#       latent_width: 4
#       output_width: 64
#     type: MLP
#     file: /global/homes/a/archis/adept/models/tpd-vae.eqx
opt:
  learning_rate: 0.1
  optimizer: adam
save:
  t:
    dt: 100fs
    tmax: 3ps
    tmin: 0ps
  x:
    dx: 128nm

  y:
    dy: 128nm

terms:
  epw:
    boundary:
      x: absorbing
      y: periodic
    density_gradient: true
    kinetic real part: false
    linear: true
    source:
      noise: true
      tpd: true
    trapping:
      active: false
      kld: 0.28
      nuee: 1.0e-07
units:
  atomic number: 40
  envelope density: 0.25
  ionization state: 6
  laser intensity: 5.0e+15W/cm^2
  laser wavelength: 351nm
  reference electron temperature: 4000eV
  reference ion temperature: 1000eV