drivers:
  ex:
    '0':
      a0: 0.01
      dw0: 0.0
      k0: 0.32
      t_c: 40.0
      t_r: 5.0
      t_w: 40.0
      w0: 1.1433284742365162
      x_c: 400.0
      x_r: 10.0
      x_w: 1000000.0
grid:
  nx: 16
  tmax: 500.0
  tmin: 0.0
  xmax: 19.634954084936208
  xmin: 0.0
mlflow:
  experiment: es1d-epw-test
  run: nl-fluid-noml
solver: es-1d 
models:
  file: false
  nu_g:
    activation: tanh
    depth: 4
    final_activation: tanh
    in_size: 3
    out_size: 1
    width_size: 8
physics:
  electron:
    T0: 1.0
    charge: -1.0
    gamma: kinetic
    is_on: true
    landau_damping: true
    mass: 1.0
    trapping:
      is_on: false
      kld: 0.32
      nn: 8|8
      nuee: 0.0001
  ion:
    T0: 1.0
    charge: 1.0
    gamma: 3
    is_on: false
    landau_damping: false
    mass: 1836.0
    trapping:
      is_on: false
      kld: 0.3
      nuee: 1.0e-09
  landau_damping: true
save:
  func:
    is_on: true
  kx:
    is_on: false
    kxmax: 0.32
    kxmin: 0.0
    nkx: 2
  t:
    nt: 1000
    tmax: 500.0
    tmin: 0.5
  x:
    is_on: true
    nx: 16
    xmax: 19.634954084936208
    xmin: 0.0