name: cpu-tests

on:
  pull_request:

  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Cancel in-progress tests on new commits to the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup_repo
      with:
        python-version: '3.11'
    - name: Test with pytest
      run: uv run --locked pytest tests/test_base

  test-lpse2d:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup_repo
      with:
        python-version: '3.11'
    - name: Test with pytest
      run: uv run --locked pytest tests/test_lpse2d

  test-vlasov1d:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup_repo
      with:
        python-version: '3.11'
    - name: Test with pytest
      run: uv run --locked pytest tests/test_vlasov1d

  test-vfp1d:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup_repo
      with:
        python-version: '3.11'
    - name: Test with pytest
      run: uv run --locked pytest tests/test_vfp1d

  test-spectrax1d:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup_repo
      with:
        python-version: '3.11'
    - name: Test with pytest
      run: uv run --locked pytest tests/test_spectrax1d
